package main

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

type EnumValue struct {
	Name       string
	ProtoValue int32
	CustomCode int32
}

type EnumInfo struct {
	Name   string
	Start  int
	Values []EnumValue
}

func main() {
	// 调试日志
	fmt.Println("=== protoc-gen-customcode 开始 ===")

	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		fmt.Printf("待处理文件数量: %d\n", len(gen.Files))

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			fmt.Printf("正在处理: %s\n", f.Desc.Path())
			generateFile(gen, f)
		}
		return nil
	})

	fmt.Println("=== protoc-gen-customcode 结束 ===")
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Enums) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_customcode.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-customcode. DO NOT EDIT.")
	g.P("// Source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	var allEnums []EnumInfo

	// 处理每个枚举
	for _, enum := range file.Enums {
		// 获取枚举前的注释
		start := extractStartValue(enum.Comments)
		if start == 0 {
			continue
		}

		enumInfo := EnumInfo{
			Name:  string(enum.Desc.Name()),
			Start: start,
		}

		g.P(fmt.Sprintf("// %s 自定义错误码 (start: %d)", enumInfo.Name, start))
		g.P("const (")

		for _, value := range enum.Values {
			// 计算自定义错误码: start << 16 + proto值
			customCode := (int32(start) << 16) + int32(value.Desc.Number())

			enumInfo.Values = append(enumInfo.Values, EnumValue{
				Name:       string(value.Desc.Name()),
				ProtoValue: int32(value.Desc.Number()),
				CustomCode: customCode,
			})

			// 生成常量，使用驼峰命名
			constName := toCamelCase(string(value.Desc.Name()))
			g.P(fmt.Sprintf("    %s_CustomCode = %d // %d<<16 + %d",
				constName,
				customCode,
				start,
				value.Desc.Number()))
		}
		g.P(")")
		g.P()

		allEnums = append(allEnums, enumInfo)
	}

	// 生成错误码映射表
	if len(allEnums) > 0 {
		generateErrorMappings(g, allEnums)
	}
}

func extractStartValue(comments protogen.Comments) int {
	if comments.Empty() {
		return 0
	}

	// 匹配 //start 101 或 //start=101 或 //start:101 格式
	re := regexp.MustCompile(`//start\s*[:=]?\s*(\d+)`)
	text := string(comments)

	matches := re.FindStringSubmatch(text)
	if len(matches) > 1 {
		start, err := strconv.Atoi(matches[1])
		if err == nil {
			return start
		}
	}
	return 0
}

func toCamelCase(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	for i := 0; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func generateErrorMappings(g *protogen.GeneratedFile, enums []EnumInfo) {
	g.P("// ErrorCodeToName 错误码映射表")
	g.P("var ErrorCodeToName = map[int32]string{")
	for _, enum := range enums {
		for _, value := range enum.Values {
			g.P(fmt.Sprintf("    %d: \"%s.%s\",",
				value.CustomCode,
				enum.Name,
				value.Name))
		}
	}
	g.P("}")
	g.P()

	g.P("// GetErrorMessage 获取错误信息")
	g.P("func GetErrorMessage(code int32) string {")
	g.P("    if name, ok := ErrorCodeToName[code]; ok {")
	g.P("        return name")
	g.P("    }")
	g.P("    return \"UNKNOWN_ERROR\"")
	g.P("}")
	g.P()

	g.P("// GetErrorCode 获取错误码")
	g.P("func GetErrorCode(enumName, valueName string) int32 {")
	g.P("    for code, name := range ErrorCodeToName {")
	g.P("        if name == enumName + \".\" + valueName {")
	g.P("            return code")
	g.P("        }")
	g.P("    }")
	g.P("    return 0")
	g.P("}")

	// 添加类型映射
	g.P()
	g.P("// ErrorCodeType 错误码类型")
	g.P("type ErrorCode int32")
	g.P()

	// 为每个枚举生成类型常量
	for _, enum := range enums {
		g.P(fmt.Sprintf("// %s 错误码列表", enum.Name))
		g.P("const (")
		for _, value := range enum.Values {
			constName := toCamelCase(string(value.Name))
			g.P(fmt.Sprintf("    %s ErrorCode = %d",
				constName,
				value.CustomCode))
		}
		g.P(")")
		g.P()
	}
}
